### ISSUE TITLE
display_for_field() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by aktywnitu** [callowayproject/django-categories#112]
Django 1.8 Python 3.5 and fresh django-categories app:

> 
> TypeError at /admin/categories/category/
> display_for_field() takes 2 positional arguments but 3 were given
>           
>       {% result_tree_list cl %}

**Comment by aktywnitu** [comment]
Unfortunately , it doesn't work.

**Comment by epicserve** [comment]
@aktywnitu, what are the steps to reproduce this error? Did you test this using master or are you using an official release?

**Comment by aktywnitu** [comment]
i removed last argument (empty string) from display_for_field() call and it started works.
On the master - official release has onother problem - solved in master.

**Comment by epicserve** [comment]
This should be fixed now in version 1.4.2.
