### ISSUE TITLE
RuntimeError: Model class categories.models.Category doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by hebertjulio** [callowayproject/django-categories#117]
Hi,

I take a fix when I make a migrate.

> root@0ce672f99958:/usr/src/myapp# python manage.py migrate --settings=blumm.settings.dev
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 327, in execute
>     django.setup()
>   File "/usr/local/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
>     app_config.ready()
>   File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
>     self.module.autodiscover()
>   File "/usr/local/lib/python2.7/site-packages/django/contrib/admin/**init**.py", line 26, in autodiscover
>     autodiscover_modules('admin', register_to=site)
>   File "/usr/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
>     import_module('%s.%s' % (app_config.name, module_to_search))
>   File "/usr/local/lib/python2.7/importlib/**init**.py", line 37, in import_module
>     **import**(name)
>   File "/usr/src/myapp/catalogs/admin.py", line 4, in <module>
>     from categories.admin import CategoryBaseAdmin
>   File "/usr/local/lib/python2.7/site-packages/categories/admin.py", line 7, in <module>
>     from .models import Category
>   File "/usr/local/lib/python2.7/site-packages/categories/models.py", line 21, in <module>
>     class Category(CategoryBase):
>   File "/usr/local/lib/python2.7/site-packages/mptt/models.py", line 262, in **new**
>     cls = super_new(meta, class_name, bases, class_dict)
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 102, in **new**
>     "INSTALLED_APPS." % (module, name)
> RuntimeError: Model class categories.models.Category doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

Django project settings file:

> DJANGO_APPS = (
>     'django.contrib.admin',
>     'django.contrib.auth',
>     'django.contrib.contenttypes',
>     'django.contrib.sessions',
>     'django.contrib.messages',
>     'django.contrib.staticfiles',
>     'django.contrib.sites',
>     'django.contrib.sitemaps',
> )
> THIRD_PARTY_APPS = (
>     'localflavor',
>     'crispy_forms',
>     'smart_selects',
>     'sorl.thumbnail',
>     'allauth',
>     'allauth.account',
>     'allauth.socialaccount',
>     # 'allauth.socialaccount.providers.facebook',
>     # 'categories',
>     'categories.editor',
> )
> LOCAL_APPS = (
>     'users',
>     'locations',
>     'catalogs',
>     'doubts',
> )

I create a sub class category model and following the application documentation to make install:

[to-only-subclass-categorybase](http://django-categories.readthedocs.io/en/latest/installation.html#to-only-subclass-categorybase)

**Comment by shzy2012** [comment]
if  run service with docker-compose.yml ,  remove  "APP_NAME" 

localtion: "docker-compose.yml" ==> "services" --> "$app name" --> "environment" --> "APP_NAME"
