### ISSUE TITLE
UnicodeEncodeError at /admin/categories/category/

### ISSUE THREAD

**Issue by tsadimas** [callowayproject/django-categories#123]
When i tried to add a Greek name for a category, the following error occurs
UnicodeEncodeError at /admin/categories/category/
'ascii' codec can't encode characters in position

Error during template rendering

In template ....python2.7/site-packages/categories/editor/templates/admin/editor/grappelli_tree_editor.html, error at line 46

 {% result_tree_list cl %}

**Comment by flaiming** [comment]
Same happened to me after upgrading to 1.5.1. Cannot use it this way, please fix ASAP.

**Comment by epicserve** [comment]
@flaiming please submit your pull request fixing the issue ASAP! :)

**Comment by flaiming** [comment]
@epicserve there it is :)

**Comment by tsadimas** [comment]
Thanks!

**Comment by epicserve** [comment]
This should be fixed in 1.5.2.
