### ISSUE TITLE
app list not showing

### ISSUE THREAD

**Issue by hypy13** [callowayproject/django-categories#160]
thanks for the app

i have a problem in dashboard
when i open the categories change list page

the sidebar app_list not showing
and its generally empty or null

**Comment by epicserve** [comment]
@hypy13,

More detail is needed before anyone can look into this. Some questions that would needed answered are:

1. What version of Python?
2. What version of Django?
3. Did you add  categories and  categories.editor to INSTALLED_APPS in your settings?

I'm closing for now until you can provide more detail.
