### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by miceno** [callowayproject/django-categories#89]
There are several pull request awaiting. Is the project alive?

In case it is... how should I proceed to help improving the app? Django 1.7, i18n, etc...

**Comment by christopherhan** [comment]
+1 Update for 1.7 is needed

**Comment by miceno** [comment]
Hi, Corey

Any progress on the new pull requests?

Thank you in advance.

**Comment by aaronvanderlip** [comment]
Could the original dev coordinate with people keeping the updated forks of this project so a PyPi release could be made that supports Django 1.7+ .

**Comment by coordt** [comment]
Hey everyone. I apologize for all the delays. I've had some serious health issues and I haven't been able to keep up.

What I would like is someone I could give admin access to the repo and coordinate the changes. Anyone interested?

**Comment by miceno** [comment]
@coordt Sad to hear that :(

I am interested on coordinating the changes. Please, advice on how to proceed.

**Comment by macolo** [comment]
@coordt Are you ok?

Did you decide on how to move on with this?

**Comment by rohanthacker** [comment]
Hey, Was there any result to this discussion? Do we have an new maintainer for the project?

**Comment by epicserve** [comment]
@rohanthacker, have you looked at the commit history lately? :)
