### ISSUE TITLE
django-categories 1.3b8 downgrades django-mptt, breaking Django 1.8

### ISSUE THREAD

**Issue by vdboor** [callowayproject/django-categories#94]
When django-categories 1.3b8 is installed, it downgrades django-mptt to the 0.6 release. This breaks Django 1.8 with a `AppRegistryNotReady` error. When upgrading django-mptt, everything works smooth.

**Comment by coordt** [comment]
This will be tricky as the latest version of django-mptt doesn't work well with Django 1.7 and lower. What I might have to do is make the 1.3 release for Django < 1.8 and have a 1.4 release that is for Django >= 1.8.

Thoughts?

**Comment by vdboor** [comment]
Ah, I see.

Releasing two versions is possible, though it will be a bit strange that the only difference is a dependency version in setup.py

In this rare case, perhaps keeping the mptt version "open" is better, e.g. >= 0.4, so installing django-categories doesn't enforce a downgrade. At a project level, the version could be limited in the `requirements.txt` file after all.

To protect the users, it would be possible to raise a warning from `__init__.py` when bad combinations of mptt and django are used.

Ideally, django-mptt should get fixed, but I noticed that 1.6 support is the minimum base line for them now. :-(

**Comment by cdvv7788** [comment]
as @vdboor said: pip install django-mptt --upgrade fixed the issue.
django-mptt site says it works with django-1.4.2+.
By default the app shouldn't break (as it is doing), so by default it should install the latest django-mptt version. I agree with the warning idea. The support for django 1.4 will end soon...updating it to work with the next LTS release should take priority.

**Comment by vdboor** [comment]
Any update on this issue? Right now forward compatibility is broken due to backwards compatibility.

I'd prefer to see the requirements being "open", all with ">=" instead of "==".
This would allow users to fix the bad combinations in their own projects.

Right now I simple *can't* have a project on 1.8 because of this.
My project template is even forced to 1.7 because of this issue.

**Comment by epicserve** [comment]
@vdboor, can you test and see if this is still and issue. I've merged in some changes to master that should take care of this issue.

**Comment by vdboor** [comment]
yes, this fixed the installation issues. I can install v1.4 without any issues.

@epicserve: is there any reason why `unicode-slugify` is still pinned to a specific version?

**Comment by epicserve** [comment]
@vdboor, no idea.
