### ISSUE TITLE
Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form CategoryAdminForm needs updating.

### ISSUE THREAD

**Issue by cho-is** [callowayproject/django-categories#95]
django.core.exceptions.ImproperlyConfigured

Django==1.8.2

**Comment by cho-is** [comment]
I think the one in pip is not the latest version

**Comment by nathanbiles** [comment]
any update on this? I am getting the same error

using Django 1.8.4

**Comment by ikresoft** [comment]
any update? same problem
