### ISSUE TITLE
Example project not working

### ISSUE THREAD

**Issue by juanpex** [callowayproject/django-categories#96]
git clone git@github.com:callowayproject/django-categories.git
cd django-categories
mkvirtualenv django_categories
pip install -r requirements.txt
cd example
./manage.py migrate
...
_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by cdvv7788** [comment]
This is related to an issue with django-mptt. Currently the app is forcing a downgrade. https://github.com/callowayproject/django-categories/issues/94 Just run pip install django-mptt --upgrade.

**Comment by juanpex** [comment]
I solved lookin the travis configuration and I used the same

rm *.db
cd example
./manage.py migrate --settings=settings-testing
./manage.py createsuperuser --settings=settings-testing
./manage.py runserver --settings=settings-testing

done
